omap: fix build break in dpll-44xx.c
Commit df44cbbf46c57317c6e2dfa46f8fd8b2f1820ee2 (Revert "OMAP4:
Clock: Move logic for enable/disable SD from ABE to DPLL casc")
removed some variable declarations and their users. Commit
7a9cba2f92c5c72ef9c444294f7a3a2d9fb18524 (OMAP4: Clear MEMIF
Static Dependencies on OMAP4460 devices) added code that tried
to use these variables without declaring them .

This introduced the below build break. Fix this.

  CC      arch/arm/mach-omap2/dpll-44xx.o
arch/arm/mach-omap2/dpll-44xx.c: In function 'omap4_dpll_low_power_cascade_enter':
arch/arm/mach-omap2/dpll-44xx.c:866: error: 'mask' undeclared (first use in this function)
arch/arm/mach-omap2/dpll-44xx.c:866: error: (Each undeclared identifier is reported only once
arch/arm/mach-omap2/dpll-44xx.c:866: error: for each function it appears in.)
arch/arm/mach-omap2/dpll-44xx.c: In function 'omap4_dpll_low_power_cascade_exit':
arch/arm/mach-omap2/dpll-44xx.c:1006: error: 'reg' undeclared (first use in this function)
arch/arm/mach-omap2/dpll-44xx.c:1008: error: 'mask' undeclared (first use in this function)
make[1]: *** [arch/arm/mach-omap2/dpll-44xx.o] Error 1
make: *** [arch/arm/mach-omap2/] Error 2

Change-Id: Ifc78bd5a959d6a505893a090e027521f80181522
Signed-off-by: Anand Gadiyar <gadiyar@ti.com>