omap4: fix compile breaks with panda-defconfig
arch/arm/plat-omap/cpu-omap.c:171: error:
implicit declaration of function 'omap2_get_mpuss_device'

Signed-off-by: Axel Haslam <axelhaslam@ti.com>
Signed-off-by: Vikram Pandita <vikram.pandita@ti.com>